import {useMemo,useState} from 'react';
import {Copy,Download,FileText,Hash,RefreshCw,Sparkles,Check,ArrowRight, WandSparkles,Type,Quote,ListChecks,Layers3,ChevronRight} from 'lucide-react';

type Mode='summarize'|'rewrite'|'extract'|'classify'|'transform';
type Output={title:string;content:string;items:string[]};
const seed='Remote teams often lose time because useful information is scattered across chat messages, documents, and meetings. A good writing workflow should make the important signal easier to find, reduce repetitive editing, and turn raw notes into clear communication that a person can review before sharing.';
const labels:Record<Mode,string>={summarize:'Summarize',rewrite:'Rewrite',extract:'Extract',classify:'Classify',transform:'Transform'};

function build(mode:Mode,text:string):Output{
 const clean=text.trim();
 if(!clean)return {title:'Waiting for input',content:'Add some text on the left and choose a workflow.',items:[]};
 if(mode==='summarize')return {title:'Executive summary',content:'The core message is to reduce information friction: gather scattered material, surface the useful signal, and turn it into concise communication that people can quickly review and share.',items:['Reduce information scattered across tools.','Make important signal easier to discover.','Use a reviewable output before sharing.']};
 if(mode==='rewrite')return {title:'Clearer rewrite',content:'Teams can move faster when useful information is easier to find, repetitive editing is reduced, and raw notes become concise communication that is simple to review before sharing.',items:['Clearer phrasing','Tighter structure','Professional tone']};
 if(mode==='extract')return {title:'Key information',content:'The text describes a writing workflow focused on clarity and information retrieval.',items:['Problem: information is scattered.','Goal: surface the important signal.','Outcome: clearer communication.','Constraint: human review before sharing.']};
 if(mode==='classify')return {title:'Content classification',content:'Primary intent: Productivity / Knowledge Work',items:['Category: Productivity','Tone: Practical','Audience: Teams','Confidence: High']};
 return {title:'Transformed copy',content:'Make the signal obvious. Cut the repetition. Give every reader a clear next move.',items:['Headline-ready','Concise','Action-oriented']};
}

export default function App(){
 const[mode,setMode]=useState<Mode>('summarize'),[text,setText]=useState(seed),[result,setResult]=useState<Output>(build('summarize',seed)),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
 const words=text.trim()?text.trim().split(/\\s+/).length:0; const chars=text.length; const outputWords=result.content.split(/\\s+/).length; const compression=words?Math.max(18,Math.round((1-outputWords/words)*100)):0;
 const run=()=>{setBusy(true);setTimeout(()=>{setResult(build(mode,text));setBusy(false)},650)};
 const copy=async()=>{await navigator.clipboard?.writeText([result.title,result.content,...result.items.map(i=>'• '+i)].join('\\n'));setCopied(true);setTimeout(()=>setCopied(false),1400)};
 const download=()=>{const blob=new Blob([[result.title,result.content,'',...result.items.map(i=>'• '+i)].join('\\n')],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='text-tool-output.txt';a.click()};
 const clear=()=>{setText('');setResult(build(mode,''))};
 const suggestions=['Turn this into an executive summary','Make this sound more concise','Extract decisions and action items'];
 const switchMode=(m:Mode)=>{setMode(m);setResult(build(m,text))};
 return <div className="app"><header className="top"><div className="logo"><div className="glyph">✦</div><div><b>TEXT//LAB</b><small>AI WRITING WORKBENCH</small></div></div><div className="top-note"><span/> LOCAL DEMO · READY</div><div className="top-actions"><button onClick={clear}>Clear</button><button onClick={download}><Download size={15}/> Export</button></div></header>
 <section className="hero"><div className="hero-copy"><span className="eyebrow">WRITING OPERATIONS / 01</span><h1>Less typing.<br/><em>More signal.</em></h1><p>Five focused AI workflows for summarizing, rewriting, extracting, classifying, and transforming text — built as a fast, review-first workbench.</p></div><div className="hero-orbit"><span>AI</span><i/><i/><i/></div></section>
 <nav className="mode-bar">{(Object.keys(labels) as Mode[]).map(m=><button key={m} onClick={()=>switchMode(m)} className={mode===m?'active':''}><span>{m==='summarize'?<FileText/>:m==='rewrite'?<Type/>:m==='extract'?<ListChecks/>:m==='classify'?<Layers3/>:<Sparkles/>}</span>{labels[m]}<ChevronRight size={13}/></button>)}</nav>
 <main className="workspace"><section className="input-col"><div className="section-head"><div><span>01 / SOURCE</span><h2>Give the model something to work with.</h2></div><div className="stats"><b>{words}</b> words · <b>{chars}</b> chars</div></div><div className="editor"><div className="editor-top"><span><Quote size={13}/> SOURCE TEXT</span><span>Plain text</span></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste an email, notes, article, brief or transcript…"/><div className="editor-bottom"><button onClick={()=>setText(seed)}>Load example</button><span>Nothing is uploaded from this demo.</span></div></div><div className="suggestions"><span>TRY A PROMPT</span>{suggestions.map(s=><button key={s} onClick={()=>setText(s+'\n\n'+text)}>{s}<ArrowRight size={13}/></button>)}</div><button className="run" onClick={run} disabled={busy}>{busy?<><RefreshCw className="spin"/> Processing…</>:<><WandSparkles/> Run {labels[mode].toLowerCase()} <kbd>⌘↵</kbd></>}</button></section>
 <section className="output-col"><div className="section-head"><div><span>02 / RESULT</span><h2>Review before it leaves the lab.</h2></div><div className="quality">{compression}% shorter</div></div><div className="result-card"><div className="result-top"><div className="result-kind"><Sparkles size={15}/> STRUCTURED OUTPUT</div><div className="actions"><button onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>}</button><button onClick={download}><Download size={15}/></button></div></div><div className="result-body"><h3>{result.title}</h3><p>{result.content}</p><div className="item-list">{result.items.map((x,i)=><div key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p></div>)}</div></div><div className="result-foot"><span><Check size={14}/> HUMAN REVIEW RECOMMENDED</span><span>{outputWords} output words</span></div></div><div className="workflow"><div><Hash size={15}/><b>Reusable workflow</b><p>Use the same interface for fast editorial passes instead of rebuilding prompts from scratch.</p></div><button onClick={run}>Run again <ArrowRight size={14}/></button></div></section></main>
 <footer><div><b>TEXT//LAB</b><span>Practical AI text utilities for everyday work.</span></div><div><span>React · TypeScript · Vite</span><span>No provider key required for the demo</span></div></footer></div>
}